### ISSUE TITLE
`NSArray` is not recognized in the generated file

### ISSUE THREAD

**Issue by HosamHasanRamadan** [dart-lang/native#1268]
Issue:
one of `NSTimeZone.h` functions returns `NSObject` instead of `NSArray` in the generted code.
`@property (class, readonly, copy) NSArray<NSString *> *knownTimeZoneNames;`

Actual:
`static objc.NSObject getKnownTimeZoneNames() {}`
Expected:
`static objc.NSArray getKnownTimeZoneNames() {}`

<details open><summary>ffigen config file</summary>

```yaml
name: NSTimeZone
description: NSTimeZone bindings
language: objc
output: "lib/timezone_bindings.dart"
exclude-all-by-default: true
objc-interfaces:
  include:
    - NSTimeZone
headers:
  entry-points:
    - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSTimeZone.h"

```

</details>

NSTimeZone.h:
https://pastebin.com/raw/rPNs3mTH

Generated dart file:
https://pastebin.com/raw/KFqpTjd6
