### ISSUE TITLE
Missing `CGImage` in AVFoundation generation

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/native#1417]
This may well be a config mistake rather than a bug, but if so I definitely think it's a documentation issue (unless I missed the docs too). I'm using the following config:
```
headers:
  entry-points:
    - '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFoundation.framework/Versions/A/Headers/AVFoundation.h'
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'AVAudioSession'
    - 'AVPlayer'
globals:
  include:
    - 'AVAudioSessionCategoryPlayback'
    - 'AVAudioSessionCategoryOptionMixWithOthers'
```

and the output has a bunch of `The name 'CGImage' isn't a type, so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'CGImage'.` errors. My initial guess is that this is because CGImage isn't an Obj-C interface, but if so, it seems very unintuitive that `exclude-all-by-default: true` with a couple of `include`d Obj-C types would created over **200k** lines of output of transitive types that I didn't ask for, but would not include CGImage.

(I'm not trying to use these APIs, so I'll try adjusting the config to remove this, but filing since it doesn't seem like it should be this easy to generate output that doesn't compile.)
