### ISSUE TITLE
[ffigen] Clarify docs for include/exclude rules

### ISSUE THREAD

**Issue by stuartmorgan-g** [dart-lang/native#1420]
I'm trying to temporarily work around https://github.com/dart-lang/native/issues/1416 by excluding the classes that have the type problem, since I don't currently need them. I updated my config to:
```
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'AVAudioSession'
    - 'AVPlayer'
    - 'FVPVideoPlayer'
  exclude:
    # Due to https://github.com/dart-lang/native/issues/1416
    - 'AVComposition'
    - 'AVFragmentedAsset'
    - 'AVFragmentedMovie'
    - 'AVMovie'
    - 'AVMutableComposition'
    - 'AVMutableMovie'
```

But the generated output still has those classes in it, so still doesn't compile. The README for ffigen says:

> Note: exclude overrides include.

so I would expect this to prevent the classes from being generated. It's not clear to me why it's not.
