### ISSUE TITLE
enums `as-int` still generates `.value` property call

### ISSUE THREAD

**Issue by dupuchba** [dart-lang/native#1464]
My use case fall into the enum as-int scenario (basically it can't work with enums). I am able to generates bindings as an abstract class but then it fails at runtime since depending methods still call `.value` getter on the class.
```dart
NSDateComponents components_fromDate_(
      NSCalendarUnit unitFlags, objc.NSDate date) {
    final _ret = _objc_msgSend_45(
        this.pointer, _sel_components_fromDate_, unitFlags.value, date.pointer);
    return NSDateComponents.castFromPointer(_ret, retain: true, release: true);
  }
```
here `NSCalendarUnit` is an abstract class as wanted but `unitFlags.value` is not valid since the abstract class does not have the getter.

To generate this ->
```
ffigen:
  name: NSTimeZone
  description: Bindings for NSTimeZone.
  language: objc
  output: 'lib/ns_timezone_bindings.dart'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'NSTimeZone'
      - 'NSCalendar'
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api
  enums:
    as-int:
      include:
        - NSCalendarUnit
  headers:
    entry-points:
      - '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSTimeZone.h'
      - '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSCalendar.h'
    include-directives:
      - '**NSCalendar.h'
      - '**NSTimeZone.h'
```

Also C-bindings are generated but I don't know how to use them or give them to Xcode (I've not found any doc), if someone can pinpoint me resources 
`Finished, Objective C bindings generated in /Users/baptistedupuch/Projects/cljd/project/MyApp/./lib/ns_timezone_bindings.dart.m`
