### ISSUE TITLE
Protocol methods missing from classes

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/native#1487]
(There's a bit of related discussion in https://github.com/dart-lang/native/issues/1462, but this is a distinct issue.)

I'm unable to call methods on an object that come from a protocol, even when they are required methods. The concrete case I hit is:

```objc
@interface AVAsset : NSObject <NSCopying, AVAsynchronousKeyValueLoading>
...
@end

@protocol AVAsynchronousKeyValueLoading
@required

- (AVKeyValueStatus)statusOfValueForKey:(NSString *)key error:(NSError * _Nullable * _Nullable)outError ...;

- (void)loadValuesAsynchronouslyForKeys:(NSArray<NSString *> *)keys completionHandler:(nullable void (^)(void))handler ...;
@end
```

In Obj-C code I can then of course call:
```objc
[asset statusOfValueForKey:@"tracks" error:nil] != AVKeyValueStatusLoaded
```

But that method simply doesn't exist on `AVAsset` in the ffigen output, even though it's an explicit part of the public interface.

**Comment by liamappelbe** [comment]
Looks like we're bitten by limitations of libclang again. Traversing the children of the interface declaration cursor, I find a `CXCursor_ObjCProtocolRef` for each of the protocols it implements. But there's no way of getting from the `CXCursor_ObjCProtocolRef` to the `CXCursor_ObjCProtocolDecl`. The only information on the `CXCursor_ObjCProtocolRef` is the name of the protocol (it doesn't even have a usr ID). So the best I can do is look up the protocol by name and throw an error if there's more than one protocol declared with that name. This should cover most of the use cases at least.

**Comment by stuartmorgan** [comment]
Do I need to do something special in my config to pick up the protocol? I synced to the hash with that fix, and still don't have the methods described in the original issue description.

**Comment by liamappelbe** [comment]
@stuartmorgan No, you shouldn't need to do anything. Can you send me your config? I'll see if I can repro. There might be a second bug here.

**Comment by stuartmorgan** [comment]
My actual repro case is [here](https://github.com/stuartmorgan/packages/blob/video-player-av-ffi/packages/video_player/video_player_avfoundation/ffigen_config.yaml), but I think this should be the relevant parts (I haven't set up a clean test with this though):

```
name: Foo
description: Test
language: objc
output:
  bindings: 'ffi_bindings.dart'
  objc-bindings: 'ffi_bindings.dart.m'
headers:
  entry-points:
    - '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVFoundation.h'
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'AVAudioSession'
    - 'AVMutableVideoCompositionInstruction'
    - 'AVMutableVideoCompositionLayerInstruction'
    - 'AVPlayer'
    - 'AVPlayerLayer'
enums:
  include:
    - 'AVAudioSessionCategoryOptions'
```
