### ISSUE TITLE
[ffigen] Regression: v14.0.0 does not generate bindings with a "plain" `include-directives`

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/native#1543]
@dcharkes I tried looking around some commits and the changelog, but couldn't find where this was introduced intentionally.

In v13.0.0: 
```yaml
name: Bindings
output: 'lib/generated_bindings.dart'
headers:
  entry-points:
    - 'src/temp.h'
  include-directives:
    - 'src/temp.h'
 ```
is enough to generate bindings. In v14.0.0, this generates a blank file. Instead, you need: 
```yaml
  include-directives:
    - '**/src/temp.h'
 ```

Seems like a pretty big bug to me, as it was causing all of my bindings to delete themselves upon re-generation. 

<details> 
<summary>Here is my <code>dart info</code></summary> 

```console
#### General info

- Dart 3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on "windows_x64"
- on windows / "Windows 10 Home" 10.0 (Build 22631)
- locale is en-US
```

</details>
