### ISSUE TITLE
Can't access `CFString` declaration

### ISSUE THREAD

**Issue by stuartmorgan-g** [dart-lang/native#1548]
The underlying type of `CFStringRef` is `struct __CFString`, and that's what ffigen is using as-is. Since it starts with `_`, it's private to the generated file, so it can't be used, even though it's part of the return type of some things it generates. E.g.:

```dart
ffi.Pointer<__CFString> get kCVPixelBufferPixelFormatTypeKey => _kCVPixelBufferPixelFormatTypeKey.value
```

Maybe that should be automatically changed to `CFStringRef` by the generator?

**Comment by liamappelbe** [comment]
The usual fix for this is to add a rename rule:

```yaml
structs:
  rename:
    # Removes prefix underscores
    # from all structures.
    '_(.*)': '$1'
  member-rename:
    '.*': # Matches any struct.
      # Removes prefix underscores
      # from members.
      '_(.*)': '$1'
```

I guess we could add a default rename rule for this, if none are specified. That might be more confusing for users though.
