### ISSUE TITLE
[Help Wanted] Using JNIGen to build a package

### ISSUE THREAD

**Issue by Leylan24** [dart-lang/native#1625]
I have custom native java code that i interact with through a method channel from flutter. I reuse this plugin through multiple apps. I would like to use JNIGen to use this same java source code, however when trying to run it I get the error 

```
(jnigen) INFO: trying to obtain gradle dependencies [getReleaseCompileClasspath]...
(jnigen) INFO: Restoring build scripts
Unhandled exception:


gradle exited with status 1
. This can be because the Android build is not yet cached. Please run `flutter build apk` in .\ and try again

#0      AndroidSdkTools._runGradleStub (package:jnigen/src/tools/android_sdk_tools.dart:207:7)
#1      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:144:7)
#2      getSummary (package:jnigen/src/summary/summary.dart:136:34)
#3      generateJniBindings (package:jnigen/src/generate_bindings.dart:31:21)
<asynchronous suspension>
#4      main (file:///D:/Pub/Cache/hosted/pub.dev/jnigen-0.12.0/bin/jnigen.dart:18:3)
<asynchronous suspension>
```

however I cannot run flutter build apk as its not yet in a example project. Would it be possible to have the java and bindings generated into a plugin/package that I can export into other applications and use it there ?

**Comment by HosseinYousefi** [comment]
If you have access to the source, you can pass the path to the source directly to JNIgen instead. If you want to use gradle, you should create an example app, pass in the path to it like https://github.com/dart-lang/http/blob/master/pkgs/cronet_http/jnigen.yaml#L3-L5 and run `flutter build apk` for the example app for gradle to download and cache the dependencies.

**Comment by Leylan24** [comment]
how would i pass it directily? My yaml file looks like this:

```
source_path:
  - 'android/src/main/java/za/co/scotchsoftware/asmart_v2_api/pay_api_driver/PayApiSystem.java'
classes:
  - 'za.co.scotchsoftware.asmart_v2_api.pay_api_driver.PayApiSystem'

output:
  dart:
    path: 'lib/jni_generated.dart'
    ## Output to single file instead of recreating source's file structure.
    ## This will be useful to reduce clutter when binding a small number of
    ## classes.
    structure: 'single_file'
```

I removed the lines:

```
android_sdk_config:
  add_gradle_deps: true
  add_gradle_sources: true
```

I get the error:

```
maven exited with 1
(jnigen) INFO: execute java -jar .dart_tool/jnigen/ApiSummarizer.jar -s "android\src\main\java\za\co\scotchsoftware\asmart_v2_api\pay_api_driver\PayApiSystem.java" za.co.scotchsoftware.asmart_v2_api.pay_api_driver.PayApiSystem
Error: Unable to access jarfile .dart_tool/jnigen/ApiSummarizer.jar

Fatal: Cannot generate summary: FormatException: Unexpected end of input (at character 1)

^

```
