### ISSUE TITLE
[ffigen] Variadic arguments with function types.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1732]
@dcharkes is there a way to do variadic arguments that are functions? trying to generate libcurl bindings  

```c
CURL_EXTERN CURLcode curl_easy_setopt(CURL *curl, CURLoption option, ...);
```

and a version of the function accepts a 
```c
static size_t curl_callback(char *data, size_t size, size_t nmemb, void *clientp)
```

```yaml

 functions:
    variadic-arguments:
      curl_easy_setopt:
        - [ 'long' ]
        - [ 'char*' ]
        - [ 'curl_off_t' ]
        - [ 'size_t curl_callback(char *data, size_t size, size_t nmemb, void *clientp)' ] <- this is what i want to somehow represent
```

_Originally posted by @kingwill101 in https://github.com/dart-lang/native/issues/238#issuecomment-2439845973_

@liamappelbe I suppose we don't support defining new types yet?

Now that we're starting to move into the visitor-world instead of yaml-config-world, could we conceivably add something for that?

@kingwill101 A possible work around would be to make a typedef for the function type in a separate header file, and add that header file to your FFIgen config, and use the typedef name as the type.
