### ISSUE TITLE
Can not generate BuildConfig class.

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#1784]
We need to use the BuildConfig class to get the `versionName` and `versionCode` of a package.

``` Kotlin
this.versionName = com.xxx.xxx.BuildConfig.VERSION_NAME
this.versionCode = com.xxx.xxx.BuildConfig.VERSION_CODE
```

The corresponding jnigen.yaml

``` YAML
# Run with `dart run jnigen --config jnigen.yaml`.
android_sdk_config:
  add_gradle_deps: true
suspend_fun_to_async: true
output:
  dart:
    path: lib/jni/
log_level: all
classes:
  - com.xxx.xxx.BuildConfig
```

The command throws error like this:

``` shell
Building package executable... (2.2s)
Built jnigen:jnigen.
(jnigen) INFO: ApiSummarizer.jar exists. Skipping build..
(jnigen) FINE: Set log level: ALL
(jnigen) INFO: trying to obtain gradle dependencies [getReleaseCompileClasspath]...
(jnigen) FINER: Writing temporary gradle script with stub "getReleaseCompileClasspath"...
(jnigen) FINER: Running gradle wrapper...
(jnigen) INFO: Restoring build scripts
(jnigen) FINE: Found 1 entries
(jnigen) INFO: execute java -jar .dart_tool/jnigen/ApiSummarizer.jar -c "C:\Users\yanshouwang\AppData\Local\Android\sdk\platforms\android-34\android.jar" com.xxx.xxx.BuildConfig
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Not found: [com.xxx.xxx.BuildConfig]

Fatal: Cannot generate summary: FormatException: Unexpected end of input (at character 1)

^

```
