### ISSUE TITLE
`include-transitive-objc-categories` not working for `NSURL` categories

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/native#1820]
I was missing some `NSURL` methods, and found that they were in a category in NSURL.h. Based on [this comment](https://github.com/dart-lang/native/issues/271#issuecomment-2453685104) and the description of https://github.com/dart-lang/native/pull/1690 I expected them to automatically be there:

```yaml
name: FoundationPathProvider
description: Bindings for NSFileManager.
language: objc
output:
  bindings: 'lib/src/ffi_bindings.dart'
headers:
  entry-points:
    - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h'
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'NSBundle'
    - 'NSFileManager'
    - 'NSURL'
```

They were not, however (using ffigen `16.0.0`). I tried adding `include-transitive-objc-categories: true` explicitly, and that didn't help. But when I added
```yaml
objc-categories:
  include:
    - 'NSURLPathUtilities'
```

they showed up. I would not expect that to be necessary.
