### ISSUE TITLE
flutter run jnigen fails in project using pub workspaces

### ISSUE THREAD

**Issue by orestesgaolin** [dart-lang/native#1900]
Trying to run `dart run` fails if package depends on Flutter, which is expected.

```sh
native/pkgs/jnigen/example/notification_plugin
❯ dart run jnigen --config jnigen.yaml
Resolving dependencies in `/.../native/pkgs/jnigen/example/notification_plugin`...
Because notification_plugin requires the Flutter SDK, version solving failed.

Flutter users should use `flutter pub` instead of `dart pub`.
```

Relevant docs: https://github.com/dart-lang/native/blob/87ef39155f48662f1cc157d97a7922e8bcd7de1d/pkgs/jnigen/README.md?plain=1#L199

However, trying to run `flutter pub run jnigen` when package is in the [pub workspace](https://dart.dev/tools/pub/workspaces) context also fails, you can use [this repository](https://github.com/orestesgaolin/native_interop_presentation/tree/main/pdf_viewer) as an example

```sh
/pdf_viewer/packages/pdf
❯ flutter pub run jnigen --config jnigen.yaml
Deprecated. Use `dart run` instead.
Package "jnigen" is not an immediate dependency.
Cannot run executables in transitive dependencies.
Failed to update packages.
```

Relevant pubspec.yaml

```yaml
name: pdf

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  jni: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jnigen: ^0.13.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        package: com.example.pdf
        pluginClass: PDFViewFlutterPlugin
```

Is it possible to use `flutter pub run jnigen` in project that uses [pub workspaces](https://dart.dev/tools/pub/workspaces)?
