### ISSUE TITLE
`NSTimeZone.secondsFromGMT` missing from generated code

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/native#209]
https://developer.apple.com/documentation/foundation/nstimezone/1387221-secondsfromgmt?language=objc

It's a readonly property, so it should show up as a getter on the Dart wrapper class.

```yaml
  objc-interfaces:
    include:
      - "NSTimeZone"
      - "NSDate"
  headers:
    entry-points:
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSTimeZone.h"
```
