### ISSUE TITLE
Generating bindings to iOS core Objective-C APIs (e.g. WidgetKit, MetricKit, HealthKit)

### ISSUE THREAD

**Issue by orestesgaolin** [dart-lang/native#2104]
I'm trying to understand if I can use `ffigen` and `objective_c` to generate bindings to some of the iOS APIs e.g. to ask for permissions or to update home screen widget. 

These are iOS-specific APIs and the [example is using SDK for macOS](https://github.com/dart-lang/native/blob/main/pkgs/ffigen/example/objective_c/config.yaml). WidgetKit can be found under `/Library/Developer/CommandLineTools/SDKs/MacOSX15.1.sdk/System/iOSSupport/System/Library/Frameworks/WidgetKit.framework/Versions/A/Modules/WidgetKit.swiftmodule/arm64e-apple-ios-macabi.swiftinterface` or `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/iOSSupport/System/Library/Frameworks/WidgetKit.framework/Versions/A/Headers/WidgetKit.h` but I'm not sure if this is even possible to generate bindings for? 

When I tried to use objective_c example with following config I didn't get anything new:

```
# yaml-language-server: $schema=../../ffigen.schema.json

name: AVFAudio
description: Bindings for AVFAudio.
language: objc
output: 'avf_audio_bindings.dart'
exclude-all-by-default: true
objc-interfaces:
  include:
    - 'AVAudioPlayer'
    - 'WidgetCenter'
headers:
  entry-points:
    - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFAudio.framework/Headers/AVAudioPlayer.h'
    - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/iOSSupport/System/Library/Frameworks/WidgetKit.framework/Versions/A/Headers/WidgetKit.h'
```

How could I generate bindings to any of the core iOS technologies?
