### ISSUE TITLE
jnigen fails for new build.gradle.kts

### ISSUE THREAD

**Issue by dupuchba** [dart-lang/native#2156]
I had working mappings up until I upgraded jnigen & jni to 14.0.1
I only generates mappings for platform SDKs, source_path is really optional here but it was working before.

I got this error:

```
(jnigen) INFO: Building ApiSummarizer component. This might take some time. The build will be cached for subsequent runs.
(jnigen) FINE: Set log level: ALL
(jnigen) INFO: trying to obtain gradle dependencies [getReleaseCompileClasspath]...
Unhandled exception:
PathNotFoundException: Cannot open file, path = './android/build.gradle' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:782:7)
#1      _File.openSync (dart:io/file_impl.dart:575:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:663:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:718:18)
#4      AndroidSdkTools._runGradleStub (package:jnigen/src/tools/android_sdk_tools.dart:184:30)
#5      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:144:7)
#6      getSummary (package:jnigen/src/summary/summary.dart:136:34)
#7      generateJniBindings (package:jnigen/src/generate_bindings.dart:35:21)
<asynchronous suspension>
#8      main (file:///Users/baptistedupuch/.pub-cache/hosted/pub.dev/jnigen-0.14.1/bin/jnigen.dart:18:3)
```

with this config

```
android_sdk_config:
  add_gradle_deps: true

output:
  # c:
  #   library_name: time_zone_bindings
  #   path: src/
  #   subdir: time_zone_bindings/
  dart:
    path: lib/time_zone_bindings.dart
    structure: single_file

source_path:
  - 'android/app/src/main/java'

classes:
  - 'android.icu.util.TimeZone'
  - 'android.icu.util.GregorianCalendar'
  - 'android.icu.util.Calendar'
```

**Comment by dupuchba** [comment]
note that it *will* generates the right bindings with this config without the `android_sdk_config` and with `classes`
```
output:
  dart:
    path: lib/time_zone_bindings.dart
    structure: single_file

class_path:
    - '/Users/baptistedupuch/Library/Android/sdk/platforms/android-35/android.jar'

classes:
  - 'android.icu.util.TimeZone'
  - 'android.icu.util.GregorianCalendar'
  - 'android.icu.util.Calendar'
```
