### ISSUE TITLE
LibTorrent bindings

### ISSUE THREAD

**Issue by Davenchy** [dart-lang/native#218]
I am trying to bind libtorrent using ffigen

my `ffigen.yaml`:

```yaml
# Run with `dart run ffigen --config ffigen.yaml`.
name: DartLibTorrentBindings
description: |
  Bindings for `LibTorrent`.

  Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
output: "lib/bindings_generated.dart"
headers:
  entry-points:
    - "src2/include/libtorrent/libtorrent.hpp"
preamble: |
  // ignore_for_file: always_specify_types
  // ignore_for_file: camel_case_types
  // ignore_for_file: non_constant_identifier_names
comments:
  style: any
  length: full
```

the output of `dart run ffigen --config ffigen.yaml` is:

```bash
Input Headers: [src2/include/libtorrent/libtorrent.hpp]
[SEVERE] : Header src2/include/libtorrent/libtorrent.hpp: Total errors/warnings: 1.
[SEVERE] :     src2/include/libtorrent/libtorrent.hpp:4:10: fatal error: 'libtorrent/add_torrent_params.hpp' file not found [Lexical or Preprocessor Issue]
Finished, Bindings generated in /.../flutter/projects/dart_libtorrent/lib/bindings_generated.dart
```

the `libtorrent.hpp` file is something like this

```hpp
// This header is generated by tools/gen_convenience_header.py

#include "libtorrent/add_torrent_params.hpp"
#include "libtorrent/address.hpp"
#include "libtorrent/alert.hpp"
#include "libtorrent/alert_types.hpp"
...
```

I was following this tutorial:

https://blog.logrocket.com/dart-ffi-native-libraries-flutter/
