### ISSUE TITLE
Generated code contains type errors

### ISSUE THREAD

**Issue by dickermoshe** [dart-lang/native#2218]
```
dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  jni: ^0.14.1
  meta: ^1.16.0
  objective_c: ^7.1.0
  path: ^1.9.1
  plugin_platform_interface: ^2.0.2
  xdg_directories: ^1.1.0

dev_dependencies:
  jnigen: ^0.14.1

  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
```
It seems that the generated code cannot compile.

<img width="1289" alt="Image" src="https://github.com/user-attachments/assets/f8846584-c3e3-4a50-b9ba-160df771d3d8" />
