### ISSUE TITLE
Blank bindings file for Objective-C headers via ffigen

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/native#223]
I am trying to use ffigen to generate the dart bindings for some of Apple's APIs. However, every one I have tried (with the exception of the examples in the documentation) have resulted in a blank bindings file. 

I am on a Mac, and I am am using dart version 2.19

Example 1
[Core Motions API](https://developer.apple.com/documentation/coremotion)

- Pubspec 

```
ffigen:
    name: IntentsLibrary
    language: objc
    output: "foundation_bindings.dart"
    exclude-all-by-default: true
    objc-interfaces:
      include:
        - "CMMotionManager"
    headers:
      entry-points:
        - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMMotionManager.h"
```

- Output
```
Building package executable... (1.4s)
Built ffigen:ffigen.
Running in Directory: '/Users/leighaj/dart/ffi_example/ffi_example'
[SEVERE] : Objective C support is EXPERIMENTAL. The API may change in a breaking way without notice.
[WARNING]: Prefer adding Key '[description]' to your config.
Input Headers: [/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMMotionManager.h]
[SEVERE] : Header /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMMotionManager.h: Total errors/warnings: 1.
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMMotionManager.h:77:117: warning: 'visibility' attribute ignored [Semantic Issue]
Finished, Bindings generated in /Users/leighaj/dart/ffi_example/ffi_example/foundation_bindings.dart
```

Example 2
[HealthKit](https://developer.apple.com/documentation/healthkit/hkhealthstore?language=objc)

- Pubspec
```
ffigen:
    name: IntentsLibrary
    language: objc
    output: "foundation_bindings.dart"
    exclude-all-by-default: true
    objc-interfaces:
      include:
        - "HKHealthStore"
    headers:
      entry-points:
        - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKHealthStore.h"
```

- Output
```
Building package executable... (1.5s)
Built ffigen:ffigen.
Running in Directory: '/Users/leighaj/dart/ffi_example/ffi_example'
[SEVERE] : Objective C support is EXPERIMENTAL. The API may change in a breaking way without notice.
[WARNING]: Prefer adding Key '[description]' to your config.
Input Headers: [/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKHealthStore.h, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKDefines.h]
[SEVERE] : Header /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKHealthStore.h: Total errors/warnings: 1.
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKHealthStore.h:8:9: fatal error: 'HealthKit/HKDefines.h' file not found [Lexical or Preprocessor Issue]
Finished, Bindings generated in /Users/leighaj/dart/ffi_example/ffi_example/foundation_bindings.dart
```

- Note that the HKDefines.h file is in the same directory, with the path: 
```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKDefines.h
```
       

Let me know if these should be separated into different issues! :) 

Are there specific things we should be considering when identifying potential APIs for FFI with Objective-C?
