### ISSUE TITLE
Missing NSString constructor when generating the bindings for healthkit

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/native#230]
I am using ffigen to generate the bindings for the HealthKit ObjC framework. 

Here is the pubspec.yaml:

```
ffigen:
  name: HealthKit
  description: "Create bindings for the HealthKit APIs"
  language: objc
  output: "lib/healthkit_bindings.dart"
  compiler-opts:
    - '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - "HKHealthStore"
      - "HKQuery"
  headers:
    entry-points:
      - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKHealthStore.h"
      - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKQuery.h"
```

In my dart file I am creating the library and attempting to convert a dart string to an NSString:

```
final lib = hk.HealthKit(DynamicLibrary.process());
var localeString = hk.NSString(lib, 'en_US')
```

But I get the error: `The class 'hk.NSString' doesn't have an unnamed constructor.`

Let me know if you need any more info!
