### ISSUE TITLE
Duplicate methods generated starting in 5.0.0

### ISSUE THREAD

**Issue by Jordan-Nelson** [dart-lang/native#234]
### Issue
I just updated from 4.1.3 to 5.0.0 and I see several methods are being duplicated when I re-run ffigen.

### Reproduction
Below is a simplified version of my config. With this I am getting 3 copies of `CFRelease` (named `CFRelease`, `CFRelease1`, and `CFRelease2`), as well as multiple copies other methods. The same config does not generate duplicates with version 4.1.3.

Is this expected with 5.0.0?

```yaml
output: 'lib/src/ffi/macos/core_foundation.bindings.g.dart'
name: 'CoreFoundation'
description: 'Bindings to macOS & iOS CoreFoundation types'
headers:
  entry-points:
    - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFDictionary.h'
    - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h'
    - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFData.h'
compiler-opts:
  - '-F/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks'
functions:
  include:
    - CFDictionaryCreate
    - CFDataCreate
    - CFStringGetCStringPtr
    - CFStringCreateWithCString
    - CFDataGetBytePtr
    - CFRelease
structs:
  include:
    - NONE
enums:
  include:
    - NONE
globals:
  include:
    - NONE
macros:
  include:
    - NONE
unions:
  include:
    - NONE
unnamed-enums:
  include:
    - NONE
comments: false
```
