### ISSUE TITLE
How to handle variable number of arguments?

### ISSUE THREAD

**Issue by arcticfox1919** [dart-lang/native#238]
The C library function I want to bind has some variable number of parameters, ffigen doesn't seem to handle this situation very well, is there any way?

for example:

```c
int func(int, ... ) {}
```

**Comment by kingwill101** [comment]
@dcharkes any update on this, now that https://github.com/dart-lang/sdk/issues/38578 has been completed?

**Comment by kingwill101** [comment]
I see that https://github.com/dart-lang/native/commit/79e845f7882f1f067913ac2fe61ded0ec9a9d9c7 was done but it seems to not work.

```c
int fcntl (int __fd, int __cmd, ...);
```


```dart
  int fcntl(
    int __fd,
    int __cmd,
  ) {
    return _fcntl(
      __fd,
      __cmd,
    );
  }


  late final _fcntlPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('fcntl');
  late final _fcntl = _fcntlPtr.asFunction<int Function(int, int)>();
```

**Comment by dcharkes** [comment]
If you write bindings yourself, you need to use `VarArgs` somewhere: https://api.dart.dev/stable/3.4.4/dart-ffi/VarArgs-class.html

If you want FFIgen to generate bindings, you need to configure FFIgen to do that.

```yaml
functions:
  variadic-arguments:
    myfunc:
      // Native C types are supported
      - [int, unsigned char, long*, float**]
      // Common C typedefs (stddef.h) are supported too
      - [uint8_t, intptr_t, size_t, wchar_t*]
      // Structs/Unions/Typedefs from generated code or a library import can be referred too.
      - [MyStruct*, my_custom_lib.CustomUnion]
```

* https://github.com/dart-lang/native/issues/497
* https://github.com/dart-archive/ffigen/pull/515

Since the feature is implemented, and was tracked by https://github.com/dart-lang/native/issues/497, I'll close this as duplicate issue.

Please file a new issue if you're having issues with `VarArgs` or FFIgen `variadic-arguments`.
