### ISSUE TITLE
Maybe add an option to the config to exclude everything by default

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/native#254]
We default to including everything, unless the user specifies an include/exclude rule. But for Objective-C we pretty much want to exclude everything by default, then just include a few specific interfaces. So I end up writing configs like this:

```yaml
functions:
  exclude:
    - '.*'
structs:
  exclude:
    - '.*'
unions:
  exclude:
    - '.*'
globals:
  exclude:
    - '.*'
macros:
  exclude:
    - '.*'
enums:
  exclude:
    - '.*'
unnamed-enums:
  exclude:
    - '.*'
objc-interfaces:
  include:
    - 'AVAudioPlayer'
```

It'd be nicer to be able to specify a config flag that excludes `'.*'` by default.

```yaml
exclude-everything-by-default: true
objc-interfaces:
  include:
    - 'AVAudioPlayer'
```
