### ISSUE TITLE
Question: How to generate bindings for multiple libs, where lib A depends on lib B?

### ISSUE THREAD

**Issue by Jordan-Nelson** [dart-lang/native#292]
Is there a recommended approach for generating bindings for multiple libs, where lib A depends on lib B? The best workaround I have found so far is to generate the bindings for each lib separately, and then write wrapper functions around the generated functions from lib A that use the proper types from lib B.

For example, I am generating bindings for libsecret. libsecret makes use of glib. Below is the definition of one of the core functions from libsecret.

```c
gboolean    secret_password_storev_sync    (const SecretSchema *schema,
  GHashTable *attributes,
  const gchar *collection,
  const gchar *label,
  const gchar *password,
  GCancellable *cancellable,
  GError **error);
```

with a config below

```yaml
output: 'lib/src/generated/libsecret.dart'
name: 'Libsecret'
description: 'Bindings to libsecret'
headers:
  entry-points:
    - '<path_to_libsecret>/libsecret/libsecret/secret.h'
    - '<path_to_libsecret>/libsecret/libsecret/secret-schema.h'
    - '<path_to_libsecret>/libsecret/libsecret/secret-password.h'
```

The following is generated:

```dart
int secret_password_storev_sync(
  ffi.Pointer<SecretSchema> schema,
  ffi.Pointer<ffi.Int32> attributes,
  ffi.Pointer<ffi.Int32> collection,
  ffi.Pointer<ffi.Int32> label,
  ffi.Pointer<ffi.Int32> password,
  ffi.Pointer<ffi.Int32> cancellable,
  ffi.Pointer<ffi.Pointer<ffi.Int32>> error,
) {...}
```

This isn't really what I would hope, since gchar, GHashTable, etc. are all represented as Int32 here.

If I add the following to the config

```yaml
compiler-opts:
- '-I/<path_to_glib>/'
```
I get the following:

```dart
int secret_password_storev_sync(
  ffi.Pointer<SecretSchema> schema,
  ffi.Pointer<GHashTable> attributes,
  ffi.Pointer<gchar> collection,
  ffi.Pointer<gchar> label,
  ffi.Pointer<gchar> password,
  ffi.Pointer<ffi.Int32> cancellable,
  ffi.Pointer<ffi.Pointer<GError>> error,
)
```

This is great, except for one issue. GHashTable, gchar, etc. are part of the generated `Libsecret` lib. This isn't a huge deal for the types, but glib has functions as well, which also get created as part of the generated `Libsecret` lib.

The work around I am using currently is to generate the bindings separately, and then write a wrapper function like so:

```dart
void wrapped_secret_password_storev_sync(
  Pointer<SecretSchema> schema,
  Pointer<GHashTable> attributes,
  Pointer<gchar> collection,
  Pointer<gchar> label,
  Pointer<gchar> password,
  Pointer<Int32> cancellable,
  Pointer<Pointer<GError>> error,
) {
    libsecret.secret_password_storev_sync(
      schema,
      attributes.cast(),
      collection.cast(),
      label.cast(),
      password.cast(),
      cancellable,
      error.cast(),
    );
  }
```

This works, but is sort of tedious. Is there a better approach?
