### ISSUE TITLE
[Question] How to deal with multiple ```so```(shared object) file?

### ISSUE THREAD

**Issue by StephanoGeorge** [dart-lang/native#294]
Hi, I want to use functions from different `.so` files, but ffigen only generate one class, and I can only pass one `.so` to the class.

```yaml
ffigen:
  name: FFI
  description: Bindings to ffi
  output: 'lib/generated_ffi_bindings.dart'
  headers:
    entry-points:
    - 'core/libquiche.h'
    - '/usr/include/sys/socket.h'
    - '/usr/include/netdb.h'
```

Should I create two FFI instance?

```dart
final libc = FFI(DynamicLibrary.open('/usr/lib/libc.so.6'));
libc.getaddrinfo(peerNameUTF8, peerPortUTF8, peerAddrHints, peerAddr);
final quiche = FFI(DynamicLibrary.open('lib/lib/libquiche.so'));
quiche.quiche_connect(nullptr, scID, scIDLength, peerAddr.value.ref.ai_addr, peerAddr.value.ref.ai_addrlen, nullptr);
```
