### ISSUE TITLE
Name defined both as enum and as macro is always included

### ISSUE THREAD

**Issue by lukaslihotzki** [dart-lang/native#336]
With this config, `test.dart` should be empty. At least, I shouldn't contain any macros or enums:
```
ffigen:
  output: 'test.dart'
  headers:
    entry-points:
      - test.h
  functions:
    exclude: [".*"]
  macros:
    exclude: [".*"]
  structs:
    exclude: [".*"]
  unions:
    exclude: [".*"]
  enums:
    exclude: [".*"]
  globals:
    exclude: [".*"]
```

With this `test.h`:
```
enum {
  TEST_VALUE = 0
};

#define TEST_VALUE 0
```

`TEST_VALUE` is included in `test.dart` anyway.
