### ISSUE TITLE
`pkg_ffi.Size` doesn't map to int by default

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/native#371]
After upgraded to `ffigen 5.0.0-dev.0` https://github.com/woodemi/libusb.dart/commit/0763bbd76b49600dc7cdf682c97790d715d7fe1b

flutter pub run ffigen results in `pkg_ffi.Size` in Dart funtion decleration

```dart
  ffi.Pointer<pkg_ffi.UnsignedChar> libusb_dev_mem_alloc(
    ffi.Pointer<libusb_device_handle> dev_handle,
    pkg_ffi.Size length,
  )

  int libusb_dev_mem_free(
    ffi.Pointer<libusb_device_handle> dev_handle,
    ffi.Pointer<pkg_ffi.UnsignedChar> buffer,
    pkg_ffi.Size length,
  )
```

Simple workaround on`develop` branch https://github.com/woodemi/libusb.dart/pull/21

```yaml
  type-map:
    'typedefs':
      'size_t':
        'lib': 'pkg_ffi'
        'c-type': 'Size'
        'dart-type': 'int'
```

# Environment

Flutter: Flutter 2.10.0 stable channel
OS: Windows 10, macOS 10.15.7, Ubuntu 18.04
ffigen: 5.0.0-dev.0
