### ISSUE TITLE
Impossible to exclude unnamed enums

### ISSUE THREAD

**Issue by jpnurmi** [dart-lang/native#410]
No matter what kind of inclusion and/or exclusion rules the config file has, unnamed enums, such as the one in `/usr/include/math.h`, somehow get always included into the generated Dart code.

```c
/* All floating-point numbers can be put in one of these categories.  */
enum
  {
    FP_NAN =
# define FP_NAN 0
      FP_NAN,
    FP_INFINITE =
# define FP_INFINITE 1
      FP_INFINITE,
    FP_ZERO =
# define FP_ZERO 2
      FP_ZERO,
    FP_SUBNORMAL =
# define FP_SUBNORMAL 3
      FP_SUBNORMAL,
    FP_NORMAL =
# define FP_NORMAL 4
      FP_NORMAL
  };
```

As a test case, if I run ffigen for `/usr/include/math.h` and attempt to exclude everything:

```yaml
output: 'test.dart'
headers:
  entry-points:
    - '/usr/include/math.h'
functions:
  exclude:
    - '.*'
structs:
  exclude:
    - '.*'
enums:
  exclude:
    - '.*'
macros:
  exclude:
    - '.*'
```

The unnamed enum still slips through:
```dart
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

const int FP_NAN = 0;

const int FP_INFINITE = 1;

const int FP_ZERO = 2;

const int FP_SUBNORMAL = 3;

const int FP_NORMAL = 4;
```
