### ISSUE TITLE
Non-positive array dimension

### ISSUE THREAD

**Issue by jpnurmi** [dart-lang/native#450]
Config:
```yaml
name: Foo
description: Foo
output: foo.dart
headers:
  entry-points:
    - /usr/include/x86_64-linux-gnu/sys/sysinfo.h
structs:
  include:
    - sysinfo
exclude-all-by-default: true
```

Input:
```c
/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _LINUX_SYSINFO_H
#define _LINUX_SYSINFO_H

#include <linux/types.h>

#define SI_LOAD_SHIFT	16
struct sysinfo {
	__kernel_long_t uptime;		/* Seconds since boot */
	__kernel_ulong_t loads[3];	/* 1, 5, and 15 minute load averages */
	__kernel_ulong_t totalram;	/* Total usable main memory size */
	__kernel_ulong_t freeram;	/* Available memory size */
	__kernel_ulong_t sharedram;	/* Amount of shared memory */
	__kernel_ulong_t bufferram;	/* Memory used by buffers */
	__kernel_ulong_t totalswap;	/* Total swap space size */
	__kernel_ulong_t freeswap;	/* swap space still available */
	__u16 procs;		   	/* Number of current processes */
	__u16 pad;		   	/* Explicit padding for m68k */
	__kernel_ulong_t totalhigh;	/* Total high memory size */
	__kernel_ulong_t freehigh;	/* Available high memory size */
	__u32 mem_unit;			/* Memory unit size in bytes */
	char _f[20-2*sizeof(__kernel_ulong_t)-sizeof(__u32)];	/* Padding: libc5 uses this.. */
};

#endif /* _LINUX_SYSINFO_H */
```

Output:
```dart
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class sysinfo extends ffi.Struct {
  // ...

  @ffi.Array.multi([0]) // <== non_positive_array_dimension (20 - 2 * 8 - 4 = 0)
  external ffi.Array<ffi.Char> _f;
}
```

Error:
```
  error • foo.dart:47:21 • Array dimensions must be positive numbers. Try changing the input to a positive number. •
          non_positive_array_dimension
```

Ubuntu 23.04, libclang 15.0.7-3
