### ISSUE TITLE
Member function with the same name as a type causes a clash in dart

### ISSUE THREAD

**Issue by TzviPM** [dart-lang/native#453]
I was playing around with the objective_c example and using a glob for the entrypoint: `AVFAudio.framework/**.h` instead of `AVFAudio.framework/Headers/AVAudioPlayer.h`. I noticed a few issues with the generated bindings.

The class AVAudioNode has a member:

```dart
AUAudioUnit? get AUAudioUnit
```
Dart complains, in this case with the error:

> **Warning**
> AUAudioUnit isn't a type.
> Try correcting the name to match an existing type. dart(not_a_type)

The solution is to rename the interface. Something like:
```yaml
objc-interfaces:
            include:
                - AVAudioPlayer
            rename:
                AUAudioUnit: IAUAudioUnit
```

The resulting code ends up like this:
```dart
IAUAudioUnit? get AUAudioUnit
```

which doesn't bother the dart compiler.

I think the right solution here would be to fail with an error that the user needs to manually choose a name for the interface and explicitly add it in some form of `rename` config.

Alternatively, we could perform some sort of auto-renaming in this case, but I'm not convinced that it would be a good UX to discover this silently.
