### ISSUE TITLE
ffi gen msvc errors 

### ISSUE THREAD

**Issue by zezo357** [dart-lang/native#474]
using 
```
# Run with `flutter pub run ffigen --config ffigen.yaml`.
name: PytorchFfiBindings
description: |
  Bindings for `src/pytorch_ffi.h`.

  Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
output: 'lib/pytorch_ffi_bindings_generated.dart'
headers:
  entry-points:
    - 'src/pytorch-v1.13.1/torch/csrc/jit/mobile/import.h'
  include-directives:
    - 'src/pytorch-v1.13.1/torch/csrc/jit/mobile/import.h'
    # - 'src/pytorch-v1.13.1/torch/csrc/jit/**/**/**.h'
compiler-opts:
  - '-Isrc\pytorch-v1.13.1'
preamble: |
  // ignore_for_file: always_specify_types
  // ignore_for_file: camel_case_types
  // ignore_for_file: non_constant_identifier_names
comments:
  style: any
  length: full

```

gets me this error 
```
Input Headers: [.\src\pytorch-v1.13.1\torch\csrc\jit\mobile\import.h]
[SEVERE] : Header .\src\pytorch-v1.13.1\torch\csrc\jit\mobile\import.h: Total errors/warnings: 22.
[SEVERE] :     src\pytorch-v1.13.1\torch/csrc/jit/mobile/module.h:2:10: warning: non-portable path to file '<Aten/core/jit_type.h>'; specified path differs in case from file name on disk [Lexical or Preprocessor Issue]
[SEVERE] :     src\pytorch-v1.13.1\ATen/core/jit_type.h:3:10: warning: non-portable path to file '<Aten/core/custom_class.h>'; specified path differs in case from file name on disk [Lexical or Preprocessor Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals_core.h:29:2: error: Error in C++ Standard Library usage [User-Defined Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h:346:1: error: unknown type name 'namespace' [Semantic Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h:346:1: error: expected ';' after top level declarator [Parse Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\cstdint:21:1: error: unknown type name 'namespace' [Semantic Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\cstdint:21:1: error: expected ';' after top level declarator [Parse Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\xtr1common:19:1: error: unknown type name 'namespace' [Semantic Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\xtr1common:19:1: error: expected ';' after top level declarator [Parse Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\cstdlib:23:62: error: expected function body after function declarator [Parse Issue]
[SEVERE] :     C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\malloc.h:67:48: error: unknown type name '_HEAPINFO' [Semantic Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vcruntime_exception.h:28:5: error: unknown type name 'bool' [Semantic Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vcruntime_exception.h:32:11: error: must use 'struct' tag to refer to type '__std_exception_data'
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vcruntime_exception.h:33:11: error: must use 'struct' tag to refer to type '__std_exception_data'
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vcruntime_exception.h:37:13: error: must use 'struct' tag to refer to type '__std_exception_data'
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vcruntime_exception.h:44:1: error: unknown type name 'namespace' [Semantic Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\vcruntime_exception.h:44:14: error: expected ';' after top level declarator [Parse Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\exception:207:8: error: expected identifier or '(' [Parse Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\exception:208:8: error: expected identifier or '(' [Parse Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\exception:209:8: error: expected identifier or '(' [Parse Issue]
[SEVERE] :     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\exception:210:8: error: expected identifier or '(' [Parse Issue]
[SEVERE] :     fatal error: too many errors emitted, stopping now
Finished, Bindings generated in G:\My Work HDD2\AndroidStudioProjects\pytorch_ffi\.\lib\pytorch_ffi_bindings_generated.dart
```
