### ISSUE TITLE
Gettings errors such as missing_const_final_var_or_type and implicit_this_reference_in_initializer

### ISSUE THREAD

**Issue by Cronnay** [dart-lang/native#491]
Hi!

I have copied this project: https://github.com/brickpop/flutter-rust-ffi

Made my own Rust program - just a small one.
My header file is just one row and looks like this: `void start_application(void);`
My generated dart file:
```dart
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `headers/example.h`.
class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void start_application() {
    return _start_application();
  }

  late final _start_applicationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('start_application');
  late final _start_application =
      _start_applicationPtr.asFunction<void Function()>();
}
```

I'm getting error at the last 2 rows. This is first error, and its regarding "late":
`Variables must be declared using the keywords 'const', 'final', 'var' or a type name. Try adding the name of the type of the variable or the keyword 'var'.dart(missing_const_final_var_or_type)`

Second error is regarding `_lookup<ffi.NativeFunction.....` and it says: `The instance member '_lookup' can't be accessed in an initializer. Try replacing the reference to the instance member with a different expression`

My pubspec.yml:
```
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: 4.1.3

ffigen:
  name: NativeLibrary
  description: Bindings to `headers/example.h`.
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'rust/bindings.h'
```
I'm using dart 2.16, ffigen 4.1.3. Any clue what the issue is here?
