### ISSUE TITLE
Missing iOS file when generating bindings for CMPedometer

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/native#492]
Hi! I'm trying to use generate bindings for the CMPedometer class that's part of the CoreMotion framework. But, I am just getting a blank bindings file.

Config:
```
name: PedometerBindings
description: "Bindings for CM pedometer"
language: objc
output: 'lib/pedometer_bindings_generated.dart'
compiler-opts:
  - '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'
objc-interfaces:
  include:
    - "CMPedometer"
headers:
  entry-points:
    - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMPedometer.h"

```

There are a series of Nullability Issue warnings, such as:
```
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:361:13: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [Nullability Issue]
```

As well as a Lexical or Preprocessor Issue:
```
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:10:9: fatal error: 'Foundation/NSURLHandle.h' file not found [Lexical or Preprocessor Issue]
```

Sorry in advance if I am missing something!!
