### ISSUE TITLE
Support variadic functions

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#497]
We'll be adding support for variadic functions to `dart:ffi`:

* https://github.com/dart-lang/sdk/issues/38578

_One interesting thing to think about is how this would work for bindings generation from `.h` files: It wouldn't know what specific var-args signature to use when generating method(s) for a vararg method. Either it could generate a lookup of pointer and require users to `fp.asFunction` or one would need to specify in the configuration._

_Originally posted by @mkustermann in https://github.com/dart-lang/sdk/issues/38578#issuecomment-1369696674_

Generating the function pointer would always require a cast, because a `Pointer<NativeFunction<X Function(X, VarArgs(X, X))>>` can't have the right signature. So it should probably be a `Pointer<Void>` if we go for that option. Which would result in:

```dart
somePointer.cast<NativeFunction<...>>.asFunction<...>();
```

However, that would not allow us to ever use variadic functions with static linking (`@FfiNative`) through ffigen.

Moreover, that requires the user to both write out the C type and Dart type of both the non-variadic arguments and variadic arguments.

So, I believe it would be better to specify the variadic arguments wanted in the config. That way the user only has to write out the C types, and only for the variadic arguments (not for the arguments before the `...`).

Also, since Dart doesn't have overloading, we would need to invent names if we want a function more than once. Adding a number is a bad idea, because when adding a variadic args config it might renumber, maybe we can default to appending the variadic argument types? Or default to appending the variadic argument types if there's more than one config?

```yaml
functions:
  variadic-arguments:
    'printf':
      - [uint32_t, double] # Single config generates `printf`.
```

```yaml
functions:
  variadic-arguments:
    'printf':
      - [uint32_t, double] # Generates `printfUInt32Double`.
      - [uint32_t, char*]  # Generates `printfUInt32CharPointer`.
```

```yaml
functions:
  variadic-arguments:
    'printf':
      - [uint32_t, double] # Generates `printfUInt32Double`.
      - types: [uint32_t, char*]
        postfix: 'IntString' # Generates `printfIntString`.
```

Related issue:

* https://github.com/dart-lang/native/issues/398

@mannprerak2 @mkustermann @Sunbreak WDYT? Any alternative ideas?
