### ISSUE TITLE
Enums excluded by a filter are not being excluded.

### ISSUE THREAD

**Issue by JakeSays** [dart-lang/native#499]
Given the header and ffigen config described below, I would expect the enum Foo to be excluded from the output, but it's not happening. It appears that `exclude:` on enums is being ignored. 

My ffigen version is 7.2.4.

foo.h:
```c
enum Foo
{
   one,
   two
};
```
foo.yaml:
```yaml
name: 'FooBindings'
output: 'lib/bindings/FooBindings.dart'
headers:
  entry-points:
    - 'foo.h'
enums:
  exclude:
    - Foo
```
