### ISSUE TITLE
NoSuchMethodError: The method '_mulFromInteger' was called on null.

### ISSUE THREAD

**Issue by RdeWilde** [dart-lang/native#517]
I get this error `NoSuchMethodError: The method '_mulFromInteger' was called on null.` on several include files, but I can't understand why.
I tried adding it to the header-filter excludes too, but that didn't fix it either.

What is the problem?

Source file:
```cpp
#include <netaddress.h>
```

Config:
```yaml
ffigen:
  output: 'generated_bridge.dart'
  headers:
    - 'src/example/src/example.h'
  header-filter:
    exclude:
      - 'netaddress.h'
  name: 'Bridge'
  description: 'Bridge'
  array-workaround: true
```

Last part of output:
 ```
Unhandled exception:
NoSuchMethodError: The method '_mulFromInteger' was called on null.
Receiver: null
Tried calling: _mulFromInteger(1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
dart-lang/ffigen#1      int.* (dart:core-patch/integers.dart:16:38)
dart-lang/ffigen#2      ArrayHelper.expandedArrayLength (package:ffigen/src/code_generator/struc.dart:176:33)
dart-lang/ffigen#3      ArrayHelper.declarationString (package:ffigen/src/code_generator/struc.dart:196:25)
dart-lang/ffigen#4      Struc.toBindingString (package:ffigen/src/code_generator/struc.dart:111:29)
dart-lang/ffigen#5      Writer.generate (package:ffigen/src/code_generator/writer.dart:153:17)
dart-lang/ffigen#6      Library.generate (package:ffigen/src/code_generator/library.dart:106:14)
dart-lang/ffigen#7      Library.generateFile (package:ffigen/src/code_generator/library.dart:88:28)
dart-lang/ffigen#8      main (file:///home/robert/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ffigen-0.1.2/bin/ffigen.dart:51:11)
dart-lang/ffigen#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
dart-lang/ffigen#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```
