### ISSUE TITLE
Generating async functions for Java

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [dart-lang/native#552]
The function getting generated are not Futures even tho it is supposed to be.
<img width="657" alt="image" src="https://github.com/dart-lang/jnigen/assets/113885801/9c1d653a-bd52-42d1-9237-7391c47a1a87">
This function should be awaited.

Code: [here](https://github.com/Gaurav-CareMonitor/ihealth-flutter/tree/main)	

Here is the yaml file:
```

# Generating from gradle dependencies
android_sdk_config:
  add_gradle_deps: true

summarizer:
  # Instead of Java source code, we want to generate from classes
  backend: asm

suspend_fun_to_async: true

output:
  c:
    library_name: health_connect
    path: src/health_connect/
  dart:
    path: lib/health_connect.dart
    structure: single_file

enable_experiment:
  - interface_implementation
```
