### ISSUE TITLE
Failed to lookup symbol 'setJniGetters': undefined symbol: setJniGetters

### ISSUE THREAD

**Issue by gergovari** [dart-lang/native#596]
Full error: `ArgumentError (Invalid argument(s): Failed to lookup symbol 'setJniGetters': undefined symbol: setJniGetters)`

Stack trace:
```
E/flutter (29324): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
E/flutter (29324): dart-lang/jnigen#1      ProtectedJniExtensions.initGeneratedLibrary (package:jni/src/jni.dart)
package:jni/src/jni.dart:1
E/flutter (29324): dart-lang/jnigen#2      jniLookup
package:lazyext/…/third_party/_init.dart:7
E/flutter (29324): dart-lang/jnigen#3      jniLookup (package:lazyext/src/third_party/_init.dart)
package:lazyext/…/third_party/_init.dart:1
E/flutter (29324): dart-lang/jnigen#4      Document._openDocument
package:lazyext/…/fitz/Document.dart:222
E/flutter (29324): dart-lang/jnigen#5      Document._openDocument (package:lazyext/src/third_party/com/artifex/mupdf/fitz/Document.dart)
package:lazyext/…/fitz/Document.dart:1
E/flutter (29324): dart-lang/jnigen#6      Document.openDocument
package:lazyext/…/fitz/Document.dart:234
E/flutter (29324): dart-lang/jnigen#7      ExerciseExtractor.getExerciseCollection
```

Running on Android 13 from Pop! OS (Ubuntu derivative) host.

jnigen.yaml:
```
android_sdk_config:
  add_gradle_deps: true
  add_gradle_sources: true

output:
  c:
    library_name: mupdf
    path: src/
    subdir: 'third_party/'
  dart:
    path: lib/src/third_party/

source_path:
  - 'android/app/src/main/java'
classes:
  - "com.artifex.mupdf.fitz.Archive"
  - "com.artifex.mupdf.fitz.Buffer"
  - "com.artifex.mupdf.fitz.ColorSpace"
  - "com.artifex.mupdf.fitz.Device"
  - "com.artifex.mupdf.fitz.Document"
  - "com.artifex.mupdf.fitz.DocumentWriter"
  - "com.artifex.mupdf.fitz.DisplayList"
  - "com.artifex.mupdf.fitz.DisplayListDevice"
  - "com.artifex.mupdf.fitz.DrawDevice"
  - "com.artifex.mupdf.fitz.Image"
  - "com.artifex.mupdf.fitz.Font"
  - "com.artifex.mupdf.fitz.Link"
  - "com.artifex.mupdf.fitz.OutlineIterator"
  - "com.artifex.mupdf.fitz.Page"
  - "com.artifex.mupdf.fitz.Path"
  - "com.artifex.mupdf.fitz.PDFAnnotation"
  - "com.artifex.mupdf.fitz.PDFDocument"
  - "com.artifex.mupdf.fitz.PDFGraftMap"
  - "com.artifex.mupdf.fitz.PDFObject"
  - "com.artifex.mupdf.fitz.PDFPage"
  - "com.artifex.mupdf.fitz.PDFWidget"
  - "com.artifex.mupdf.fitz.Pixmap"
  - "com.artifex.mupdf.fitz.Story"
  - "com.artifex.mupdf.fitz.StrokeState"
  - "com.artifex.mupdf.fitz.StructuredText"
  - "com.artifex.mupdf.fitz.Text"
  #- "com.artifex.mupdf.fitz.XML"
```

code:
```
 Future<ExerciseCollection> getExerciseCollection(File file) async {
    mupdf.Document document =
        mupdf.Document.openDocument(file.path.toJString()); // THIS TRIGGERS IT
    for (int i = 0; i < document.countPages(i); i++) {
      final page = document.loadPage(i, i);
      final text = page.toStructuredText("preserve-whitespaces".toJString());
      final blocks = text.getBlocks();
      for (int j = 0; j < blocks.length; j++) {
        final block = blocks[j];
        print(block.toString());
      }
    }
    String title = _getVisualTitle() ?? "PLACEHOLDER";
    List<Exercise> exercises = await _extractExercises(file);
    return (title, exercises);
  }
```

In order to satisfy MuPDF dependency:
android/build.gradle:
```
allprojects {
    repositories {
        google()
        mavenCentral()
	maven { url "https://maven.ghostscript.com/" }
    }
}
```

android/app/build.gradle:
```
dependencies {
    api 'com.artifex.mupdf:fitz:1.22.0'
}
```

EDIT: Is this applicable to this?
```
jnigen is unable to parse sources.
If the errors are similar to symbol not found, ensure all dependencies of the source are available. If such dependency is compiled, it can be included in class_path.
```

EDIT2: Tried dart-lang/jnigen#119, by running `dart run jni:setup`. No luck.

EDIT3: I'm starting to think that jnigen should make a .so as when I remove the old C `libmupdf.so` (it's an actual library) I get this from JNI: ``ArgumentError (Invalid argument(s): Failed to load dynamic library 'libmupdf.so': dlopen failed: library "libmupdf.so" not found)', let's try pure dart bindings!
