### ISSUE TITLE
Jnigen doesn't work when fetched from a git repository

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#690]
If we depend on `jnigen` using a git repo address in pubspec.yaml:

```yaml
  jnigen:
    git:
      url: https://github.com/dart-lang/jnigen
      ref: no-local-ref-delete
      path: ./jnigen
```

Running `dart run jnigen --config jnigen.yaml` fails:

```
Could not find a file named "pubspec.yaml" in "...".
```
