### ISSUE TITLE
ApiSummarizer fails when provided only gradle classes

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#714]
Currently this `jnigen.yaml` config fails:

```yaml
android_sdk_config:
  add_gradle_deps: true

output:
  c:
    library_name: android_utils
    path: src/android_utils/
  dart:
    path: lib/android_utils.dart
    structure: single_file

classes:
  - 'android.os.Build' # from gradle's compile classpath
```

As it does not have a source_path.
