### ISSUE TITLE
Output config structure

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#738]
> * Added `root_package` option, which allows simpler hierarchy if all classes are from same package. For example, instead of `org/apache/pdfbox/pdmodel.dart` we can create `pdmodel.dart`, by telling that root_package is `org.apache.pdfbox`.

I presume we add this because it is annoying for people. 😄 
Though, Java explicitly doesn't support this.
The question is should we make our bindings look mostly like Java or mostly like Dart? (With ffigen in C, we say that when you write code against generated bindings, you're writing C in Dart syntax. So we're okay with violating dart naming for identifiers etc. With that reasoning, maybe we should stick with the nested folders, because it is more Java-esque.)

I would like to unify everything that influences _only_ output structure in the config:

```yaml
output:
  dart:
    path: 'lib/src/third_party/pdfbox/'
    output_structure: single_file || package_structure
  c:
    ## Root for generated C bindings.
    path: 'src/'
```

Also, maybe we could clean up the C output

```yaml
output:
  dart:
    path: 'lib/src/third_party/pdfbox/'
    output_structure: single_file || package_structure
  c:
    path: 'src/third_party/' # both generated C file and makefile?
    cmake_path: 'src/' # To make Flutter happy?
```

_Originally posted by @dcharkes in https://github.com/dart-lang/jnigen/issues/87#issuecomment-1268245201_
