### ISSUE TITLE
Long term: Merge with ffigen.

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#774]
We would like to make the interface of `jnigen` and `ffigen` as close as possible. dart-lang/native#773 is also a step towards that, among other things.

In best case, jnigen would be as usable as ffigen.

Then from user perspective, the tool should be the same. ffigen already has support for C, Obj-C and Swift.

From maintainer's perspective, it would be same group of people, possibly @liamappelbe who will be maintaining both functionalities. From user's perspective, if these tools are generating same kind of file (s), and configuration also same.

Thus, if dart-lang/native#773 succeeds, next steps will be to

* Unify configuration interface of ffigen & jnigen. Preferably refactor ffigen's YAML logic into separate package.

* Merge code generation logic of jnigen into ffigen. We aren't shipping anything large in jnigen like JAR files. It would live in a separate directory.

From user's perspective, configuration will be very similar. Hypothetically something like

```
language: java
source_dirs: src/android/main
target: 'com.myApp.android_utils'

classes:
    exclude:
       - ....
    rename:
      'android.os.Process' : 'AndroidProcess'
```

I think it's a welcome change in long term from maintenance perspective, especially if same person is maintaining both.
