### ISSUE TITLE
[jnigen] Jnigen fails with FormatException

### ISSUE THREAD

**Issue by glanium** [dart-lang/native#877]
Jnigen fails with the following error.

This error message does not help me know what to do next.
What file does this error message mention about?

```
dart run jnigen --config .\jnigen.yaml
(jnigen) INFO: ApiSummarizer.jar exists. Skipping build..
(jnigen) INFO: execute java -jar .dart_tool/jnigen/ApiSummarizer.jar -c jar\okio-3.0.0.jar;jar\okhttp-4.10.0.jar --backend asm okhttp3.OkHttpClient    
Unhandled exception:
FormatException: Unexpected extension byte (at offset 1)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1852:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#9      _StreamController._add (dart:async/stream_controller.dart:658:7)
#10     _StreamController.add (dart:async/stream_controller.dart:606:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#16     _StreamController._add (dart:async/stream_controller.dart:658:7)
#17     _StreamController.add (dart:async/stream_controller.dart:606:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

```
 Flutter (Channel stable, 3.16.4, on Microsoft Windows [Version 10.0.22631.2428], locale ja-JP)
    • Flutter version 3.16.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (3 weeks ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
```

```yaml
dependencies:  
  jni: 0.7.2  

dev_dependencies:
  jnigen: 0.7.0
```

**Comment by HosseinYousefi** [comment]
Can you share your `jnigen.yaml`?

**Comment by Marco4763** [comment]
Hello @glanium, dont' know if you still facing this issue, but, from I can see from your config file, you trying to access a dependency that it is not implemented in the project, you need to fetch the dependency to be able to import it, like this:
```
summarizer:
  backend: asm

output:
  dart:
    path: lib/src/okhttp3.dart
    structure: single_file
  bindings_type: dart_only

class_path:
  - 'jar/okio-3.0.0.jar'
  - 'jar/okhttp-4.10.0.jar'

classes:
  - 'okhttp3.OkHttpClient'

#Add this lines
maven_downloads:
  source_deps:
    - "com.squareup.okhttp3:okhttp:4.12.0"
    - "com.squareup.okhttp3:logging-interceptor:4.12.0"
```

Don't forget to run **flutter build apk** before generate the bindings, tell me if this help
